#!/bin/bash
#

usage () {
  echo usage: $0 FILE1.rtf FILE2.rtf FILEx.rtf
  exit 0
}

[ "$1" = "" ] && usage


[ -f slideshow.txt ] && old slideshow.txt

for f in $@ ; do
  [ -f $f ] || {
    echo "$f does not exist - skipping..."
    continue
  }
  n=${f/\.rtf}; n=${n##*/}
  {
    echo "<section label=\"$n\">"
    sed 's/p>/para>/g
s/h2/title/g
/^<table/,/<td>/d
/<\/td/,/<\/table>/d' $f \
  | fmt
    echo "</section>"
  } > slideshow.txt
done

ls -l slideshow.txt

exit 0
