#!/bin/bash

for f in `find . -name "*.rtf"` ; do

    echo "check utf-8 of $f"

    if ! iconv --from utf-8 --to utf-8 $f > /dev/null ; then
	echo "file $f is not utf-8 encoded"
	exit 1
    fi

done

exit 0
